databases:
  - name: arav-portfolio-db
    plan: basic-256mb
    databaseName: arav_portfolio
    user: arav_portfolio

services:
  - type: web
    name: arav-portfolio
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERNAME
        value: aravadmin
      - key: ADMIN_PASSWORD
        value: AravPortfolio-Admin-2026!
      - key: DATABASE_URL
        fromDatabase:
          name: arav-portfolio-db
          property: connectionString
